/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { MindGardenBackupExportRequest, MindGardenBackupExportResult, MindGardenBackupInspectRequest, MindGardenBackupInspectResult, MindGardenBackupRestoreRequest, MindGardenBackupRestoreResult, MindGardenKeyRotationRequest, MindGardenKeyRotationResult } from '@deepseek-ai/dsh-mind-garden/portability/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6d696e6447617264656e506f72746162696c697479 {
    exportBackup: (agentId: SessionId, request: MindGardenBackupExportRequest) => Promise<RemoteResult<MindGardenBackupExportResult>>
    inspectBackup: (agentId: SessionId, request: MindGardenBackupInspectRequest) => Promise<RemoteResult<MindGardenBackupInspectResult>>
    restoreBackup: (agentId: SessionId, request: MindGardenBackupRestoreRequest) => Promise<RemoteResult<MindGardenBackupRestoreResult>>
    rotateDataKey: (agentId: SessionId, request: MindGardenKeyRotationRequest) => Promise<RemoteResult<MindGardenKeyRotationResult>>
  }
  interface TypertRemoteMap {
    'mindGardenPortability/exportBackup': (agentId: SessionId, request: MindGardenBackupExportRequest) => Promise<RemoteResult<MindGardenBackupExportResult>>
    'mindGardenPortability/inspectBackup': (agentId: SessionId, request: MindGardenBackupInspectRequest) => Promise<RemoteResult<MindGardenBackupInspectResult>>
    'mindGardenPortability/restoreBackup': (agentId: SessionId, request: MindGardenBackupRestoreRequest) => Promise<RemoteResult<MindGardenBackupRestoreResult>>
    'mindGardenPortability/rotateDataKey': (agentId: SessionId, request: MindGardenKeyRotationRequest) => Promise<RemoteResult<MindGardenKeyRotationResult>>
  }
  interface TypertRemoteNamespaceMap {
    'mindGardenPortability': TypertRemoteNamespace$6d696e6447617264656e506f72746162696c697479
  }
  interface TypertRemoteScopeMap {
    'agent:mindGardenPortability/exportBackup': (request: MindGardenBackupExportRequest) => Promise<RemoteResult<MindGardenBackupExportResult>>
    'agent:mindGardenPortability/inspectBackup': (request: MindGardenBackupInspectRequest) => Promise<RemoteResult<MindGardenBackupInspectResult>>
    'agent:mindGardenPortability/restoreBackup': (request: MindGardenBackupRestoreRequest) => Promise<RemoteResult<MindGardenBackupRestoreResult>>
    'agent:mindGardenPortability/rotateDataKey': (request: MindGardenKeyRotationRequest) => Promise<RemoteResult<MindGardenKeyRotationResult>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
