/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ActivateMindGardenRequest, MindGardenMode, MindGardenSessionState, MindGardenSupportIntent } from '@deepseek-ai/dsh-mind-garden/core/client'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6d696e6447617264656e {
    acceptModelDisclosure: (agentId: SessionId, expectedRevision: number) => Promise<RemoteResult<MindGardenSessionState>>
    activate: (agentId: SessionId, request: ActivateMindGardenRequest) => Promise<RemoteResult<MindGardenSessionState>>
    selectMode: (agentId: SessionId, expectedRevision: number, mode: MindGardenMode) => Promise<RemoteResult<MindGardenSessionState>>
    selectSupportIntent: (agentId: SessionId, expectedRevision: number, supportIntent: MindGardenSupportIntent) => Promise<RemoteResult<MindGardenSessionState>>
  }
  interface TypertRemoteMap {
    'mindGarden/acceptModelDisclosure': (agentId: SessionId, expectedRevision: number) => Promise<RemoteResult<MindGardenSessionState>>
    'mindGarden/activate': (agentId: SessionId, request: ActivateMindGardenRequest) => Promise<RemoteResult<MindGardenSessionState>>
    'mindGarden/selectMode': (agentId: SessionId, expectedRevision: number, mode: MindGardenMode) => Promise<RemoteResult<MindGardenSessionState>>
    'mindGarden/selectSupportIntent': (agentId: SessionId, expectedRevision: number, supportIntent: MindGardenSupportIntent) => Promise<RemoteResult<MindGardenSessionState>>
  }
  interface TypertRemoteNamespaceMap {
    'mindGarden': TypertRemoteNamespace$6d696e6447617264656e
  }
  interface TypertRemoteScopeMap {
    'agent:mindGarden/acceptModelDisclosure': (expectedRevision: number) => Promise<RemoteResult<MindGardenSessionState>>
    'agent:mindGarden/activate': (request: ActivateMindGardenRequest) => Promise<RemoteResult<MindGardenSessionState>>
    'agent:mindGarden/selectMode': (expectedRevision: number, mode: MindGardenMode) => Promise<RemoteResult<MindGardenSessionState>>
    'agent:mindGarden/selectSupportIntent': (expectedRevision: number, supportIntent: MindGardenSupportIntent) => Promise<RemoteResult<MindGardenSessionState>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
