/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { MindGardenMemoryAutomationPolicyResult, MindGardenMemoryConfirmRequest, MindGardenMemoryConfirmResult, MindGardenMemoryDeleteRequest, MindGardenMemoryDeleteResult, MindGardenMemoryExtractRequest, MindGardenMemoryExtractResult, MindGardenMemoryLatestAuditResult, MindGardenMemoryLatestExtractionResult, MindGardenMemoryListResult, MindGardenMemoryListRevisionsRequest, MindGardenMemoryListRevisionsResult, MindGardenMemoryProposeRequest, MindGardenMemoryProposeResult, MindGardenMemoryRejectRequest, MindGardenMemoryRejectResult, MindGardenMemoryResolveRelationshipRequest, MindGardenMemoryResolveRelationshipResult, MindGardenMemorySetAutomationPolicyRequest, MindGardenMemorySetAutomationPolicyResult, MindGardenMemoryUpdateRequest, MindGardenMemoryUpdateResult } from '@deepseek-ai/dsh-mind-garden/memory/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6d696e6447617264656e4d656d6f7279 {
    automationPolicy: (agentId: SessionId) => Promise<RemoteResult<MindGardenMemoryAutomationPolicyResult>>
    confirm: (agentId: SessionId, request: MindGardenMemoryConfirmRequest) => Promise<RemoteResult<MindGardenMemoryConfirmResult>>
    delete: (agentId: SessionId, request: MindGardenMemoryDeleteRequest) => Promise<RemoteResult<MindGardenMemoryDeleteResult>>
    extract: (agentId: SessionId, request: MindGardenMemoryExtractRequest) => Promise<RemoteResult<MindGardenMemoryExtractResult>>
    latestAudit: (agentId: SessionId) => Promise<RemoteResult<MindGardenMemoryLatestAuditResult>>
    latestExtraction: (agentId: SessionId) => Promise<RemoteResult<MindGardenMemoryLatestExtractionResult>>
    list: (agentId: SessionId) => Promise<RemoteResult<MindGardenMemoryListResult>>
    listRevisions: (agentId: SessionId, request: MindGardenMemoryListRevisionsRequest) => Promise<RemoteResult<MindGardenMemoryListRevisionsResult>>
    propose: (agentId: SessionId, request: MindGardenMemoryProposeRequest) => Promise<RemoteResult<MindGardenMemoryProposeResult>>
    reject: (agentId: SessionId, request: MindGardenMemoryRejectRequest) => Promise<RemoteResult<MindGardenMemoryRejectResult>>
    resolveRelationship: (agentId: SessionId, request: MindGardenMemoryResolveRelationshipRequest) => Promise<RemoteResult<MindGardenMemoryResolveRelationshipResult>>
    setAutomationPolicy: (agentId: SessionId, request: MindGardenMemorySetAutomationPolicyRequest) => Promise<RemoteResult<MindGardenMemorySetAutomationPolicyResult>>
    update: (agentId: SessionId, request: MindGardenMemoryUpdateRequest) => Promise<RemoteResult<MindGardenMemoryUpdateResult>>
  }
  interface TypertRemoteMap {
    'mindGardenMemory/automationPolicy': (agentId: SessionId) => Promise<RemoteResult<MindGardenMemoryAutomationPolicyResult>>
    'mindGardenMemory/confirm': (agentId: SessionId, request: MindGardenMemoryConfirmRequest) => Promise<RemoteResult<MindGardenMemoryConfirmResult>>
    'mindGardenMemory/delete': (agentId: SessionId, request: MindGardenMemoryDeleteRequest) => Promise<RemoteResult<MindGardenMemoryDeleteResult>>
    'mindGardenMemory/extract': (agentId: SessionId, request: MindGardenMemoryExtractRequest) => Promise<RemoteResult<MindGardenMemoryExtractResult>>
    'mindGardenMemory/latestAudit': (agentId: SessionId) => Promise<RemoteResult<MindGardenMemoryLatestAuditResult>>
    'mindGardenMemory/latestExtraction': (agentId: SessionId) => Promise<RemoteResult<MindGardenMemoryLatestExtractionResult>>
    'mindGardenMemory/list': (agentId: SessionId) => Promise<RemoteResult<MindGardenMemoryListResult>>
    'mindGardenMemory/listRevisions': (agentId: SessionId, request: MindGardenMemoryListRevisionsRequest) => Promise<RemoteResult<MindGardenMemoryListRevisionsResult>>
    'mindGardenMemory/propose': (agentId: SessionId, request: MindGardenMemoryProposeRequest) => Promise<RemoteResult<MindGardenMemoryProposeResult>>
    'mindGardenMemory/reject': (agentId: SessionId, request: MindGardenMemoryRejectRequest) => Promise<RemoteResult<MindGardenMemoryRejectResult>>
    'mindGardenMemory/resolveRelationship': (agentId: SessionId, request: MindGardenMemoryResolveRelationshipRequest) => Promise<RemoteResult<MindGardenMemoryResolveRelationshipResult>>
    'mindGardenMemory/setAutomationPolicy': (agentId: SessionId, request: MindGardenMemorySetAutomationPolicyRequest) => Promise<RemoteResult<MindGardenMemorySetAutomationPolicyResult>>
    'mindGardenMemory/update': (agentId: SessionId, request: MindGardenMemoryUpdateRequest) => Promise<RemoteResult<MindGardenMemoryUpdateResult>>
  }
  interface TypertRemoteNamespaceMap {
    'mindGardenMemory': TypertRemoteNamespace$6d696e6447617264656e4d656d6f7279
  }
  interface TypertRemoteScopeMap {
    'agent:mindGardenMemory/automationPolicy': () => Promise<RemoteResult<MindGardenMemoryAutomationPolicyResult>>
    'agent:mindGardenMemory/confirm': (request: MindGardenMemoryConfirmRequest) => Promise<RemoteResult<MindGardenMemoryConfirmResult>>
    'agent:mindGardenMemory/delete': (request: MindGardenMemoryDeleteRequest) => Promise<RemoteResult<MindGardenMemoryDeleteResult>>
    'agent:mindGardenMemory/extract': (request: MindGardenMemoryExtractRequest) => Promise<RemoteResult<MindGardenMemoryExtractResult>>
    'agent:mindGardenMemory/latestAudit': () => Promise<RemoteResult<MindGardenMemoryLatestAuditResult>>
    'agent:mindGardenMemory/latestExtraction': () => Promise<RemoteResult<MindGardenMemoryLatestExtractionResult>>
    'agent:mindGardenMemory/list': () => Promise<RemoteResult<MindGardenMemoryListResult>>
    'agent:mindGardenMemory/listRevisions': (request: MindGardenMemoryListRevisionsRequest) => Promise<RemoteResult<MindGardenMemoryListRevisionsResult>>
    'agent:mindGardenMemory/propose': (request: MindGardenMemoryProposeRequest) => Promise<RemoteResult<MindGardenMemoryProposeResult>>
    'agent:mindGardenMemory/reject': (request: MindGardenMemoryRejectRequest) => Promise<RemoteResult<MindGardenMemoryRejectResult>>
    'agent:mindGardenMemory/resolveRelationship': (request: MindGardenMemoryResolveRelationshipRequest) => Promise<RemoteResult<MindGardenMemoryResolveRelationshipResult>>
    'agent:mindGardenMemory/setAutomationPolicy': (request: MindGardenMemorySetAutomationPolicyRequest) => Promise<RemoteResult<MindGardenMemorySetAutomationPolicyResult>>
    'agent:mindGardenMemory/update': (request: MindGardenMemoryUpdateRequest) => Promise<RemoteResult<MindGardenMemoryUpdateResult>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
