/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { MindGardenApplyStarCardRevisionRequest, MindGardenApplyStarCardRevisionResult, MindGardenCalibrateStarCardRequest, MindGardenCalibrateStarCardResult, MindGardenCompleteStarRitualRequest, MindGardenCompleteStarRitualResult, MindGardenContinueStarCardRequest, MindGardenContinueStarCardResult, MindGardenDrawStarCardRequest, MindGardenDrawStarCardResult, MindGardenFinalizeStarCardRequest, MindGardenFinalizeStarCardResult, MindGardenSaveStarRitualRequest, MindGardenSaveStarRitualResult, MindGardenStarMapOverviewResult, MindGardenUpdateStarProfileRequest, MindGardenUpdateStarProfileResult, MindGardenUpdateStarTraitRequest, MindGardenUpdateStarTraitResult } from '@deepseek-ai/dsh-mind-garden/star-map/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6d696e6447617264656e537461724d6170 {
    applyCardRevision: (agentId: SessionId, request: MindGardenApplyStarCardRevisionRequest) => Promise<RemoteResult<MindGardenApplyStarCardRevisionResult>>
    calibrateCard: (agentId: SessionId, request: MindGardenCalibrateStarCardRequest) => Promise<RemoteResult<MindGardenCalibrateStarCardResult>>
    completeRitual: (agentId: SessionId, request: MindGardenCompleteStarRitualRequest) => Promise<RemoteResult<MindGardenCompleteStarRitualResult>>
    continueCard: (agentId: SessionId, request: MindGardenContinueStarCardRequest) => Promise<RemoteResult<MindGardenContinueStarCardResult>>
    drawCard: (agentId: SessionId, request: MindGardenDrawStarCardRequest) => Promise<RemoteResult<MindGardenDrawStarCardResult>>
    finalizeCard: (agentId: SessionId, request: MindGardenFinalizeStarCardRequest) => Promise<RemoteResult<MindGardenFinalizeStarCardResult>>
    overview: (agentId: SessionId) => Promise<RemoteResult<MindGardenStarMapOverviewResult>>
    saveRitualProgress: (agentId: SessionId, request: MindGardenSaveStarRitualRequest) => Promise<RemoteResult<MindGardenSaveStarRitualResult>>
    updateProfile: (agentId: SessionId, request: MindGardenUpdateStarProfileRequest) => Promise<RemoteResult<MindGardenUpdateStarProfileResult>>
    updateTrait: (agentId: SessionId, request: MindGardenUpdateStarTraitRequest) => Promise<RemoteResult<MindGardenUpdateStarTraitResult>>
  }
  interface TypertRemoteMap {
    'mindGardenStarMap/applyCardRevision': (agentId: SessionId, request: MindGardenApplyStarCardRevisionRequest) => Promise<RemoteResult<MindGardenApplyStarCardRevisionResult>>
    'mindGardenStarMap/calibrateCard': (agentId: SessionId, request: MindGardenCalibrateStarCardRequest) => Promise<RemoteResult<MindGardenCalibrateStarCardResult>>
    'mindGardenStarMap/completeRitual': (agentId: SessionId, request: MindGardenCompleteStarRitualRequest) => Promise<RemoteResult<MindGardenCompleteStarRitualResult>>
    'mindGardenStarMap/continueCard': (agentId: SessionId, request: MindGardenContinueStarCardRequest) => Promise<RemoteResult<MindGardenContinueStarCardResult>>
    'mindGardenStarMap/drawCard': (agentId: SessionId, request: MindGardenDrawStarCardRequest) => Promise<RemoteResult<MindGardenDrawStarCardResult>>
    'mindGardenStarMap/finalizeCard': (agentId: SessionId, request: MindGardenFinalizeStarCardRequest) => Promise<RemoteResult<MindGardenFinalizeStarCardResult>>
    'mindGardenStarMap/overview': (agentId: SessionId) => Promise<RemoteResult<MindGardenStarMapOverviewResult>>
    'mindGardenStarMap/saveRitualProgress': (agentId: SessionId, request: MindGardenSaveStarRitualRequest) => Promise<RemoteResult<MindGardenSaveStarRitualResult>>
    'mindGardenStarMap/updateProfile': (agentId: SessionId, request: MindGardenUpdateStarProfileRequest) => Promise<RemoteResult<MindGardenUpdateStarProfileResult>>
    'mindGardenStarMap/updateTrait': (agentId: SessionId, request: MindGardenUpdateStarTraitRequest) => Promise<RemoteResult<MindGardenUpdateStarTraitResult>>
  }
  interface TypertRemoteNamespaceMap {
    'mindGardenStarMap': TypertRemoteNamespace$6d696e6447617264656e537461724d6170
  }
  interface TypertRemoteScopeMap {
    'agent:mindGardenStarMap/applyCardRevision': (request: MindGardenApplyStarCardRevisionRequest) => Promise<RemoteResult<MindGardenApplyStarCardRevisionResult>>
    'agent:mindGardenStarMap/calibrateCard': (request: MindGardenCalibrateStarCardRequest) => Promise<RemoteResult<MindGardenCalibrateStarCardResult>>
    'agent:mindGardenStarMap/completeRitual': (request: MindGardenCompleteStarRitualRequest) => Promise<RemoteResult<MindGardenCompleteStarRitualResult>>
    'agent:mindGardenStarMap/continueCard': (request: MindGardenContinueStarCardRequest) => Promise<RemoteResult<MindGardenContinueStarCardResult>>
    'agent:mindGardenStarMap/drawCard': (request: MindGardenDrawStarCardRequest) => Promise<RemoteResult<MindGardenDrawStarCardResult>>
    'agent:mindGardenStarMap/finalizeCard': (request: MindGardenFinalizeStarCardRequest) => Promise<RemoteResult<MindGardenFinalizeStarCardResult>>
    'agent:mindGardenStarMap/overview': () => Promise<RemoteResult<MindGardenStarMapOverviewResult>>
    'agent:mindGardenStarMap/saveRitualProgress': (request: MindGardenSaveStarRitualRequest) => Promise<RemoteResult<MindGardenSaveStarRitualResult>>
    'agent:mindGardenStarMap/updateProfile': (request: MindGardenUpdateStarProfileRequest) => Promise<RemoteResult<MindGardenUpdateStarProfileResult>>
    'agent:mindGardenStarMap/updateTrait': (request: MindGardenUpdateStarTraitRequest) => Promise<RemoteResult<MindGardenUpdateStarTraitResult>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
