/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { MindGardenContinuePhotoStoryRequest, MindGardenContinuePhotoStoryResult, MindGardenCreatePhotoStoryRequest, MindGardenCreatePhotoStoryResult, MindGardenDeletePhotoStoryRequest, MindGardenDeletePhotoStoryResult, MindGardenListPhotoStoriesRequest, MindGardenListPhotoStoriesResult, MindGardenObservePhotoStoryRequest, MindGardenObservePhotoStoryResult, MindGardenReadPhotoStoryRequest, MindGardenReadPhotoStoryResult, MindGardenUpdatePhotoStoryRequest, MindGardenUpdatePhotoStoryResult } from '@deepseek-ai/dsh-mind-garden/media/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6d696e6447617264656e4d65646961 {
    continuePhotoStory: (agentId: SessionId, request: MindGardenContinuePhotoStoryRequest) => Promise<RemoteResult<MindGardenContinuePhotoStoryResult>>
    createPhotoStory: (agentId: SessionId, request: MindGardenCreatePhotoStoryRequest) => Promise<RemoteResult<MindGardenCreatePhotoStoryResult>>
    deletePhotoStory: (agentId: SessionId, request: MindGardenDeletePhotoStoryRequest) => Promise<RemoteResult<MindGardenDeletePhotoStoryResult>>
    listPhotoStories: (agentId: SessionId, request: MindGardenListPhotoStoriesRequest) => Promise<RemoteResult<MindGardenListPhotoStoriesResult>>
    observePhotoStory: (agentId: SessionId, request: MindGardenObservePhotoStoryRequest) => Promise<RemoteResult<MindGardenObservePhotoStoryResult>>
    readPhotoStory: (agentId: SessionId, request: MindGardenReadPhotoStoryRequest) => Promise<RemoteResult<MindGardenReadPhotoStoryResult>>
    updatePhotoStory: (agentId: SessionId, request: MindGardenUpdatePhotoStoryRequest) => Promise<RemoteResult<MindGardenUpdatePhotoStoryResult>>
  }
  interface TypertRemoteMap {
    'mindGardenMedia/continuePhotoStory': (agentId: SessionId, request: MindGardenContinuePhotoStoryRequest) => Promise<RemoteResult<MindGardenContinuePhotoStoryResult>>
    'mindGardenMedia/createPhotoStory': (agentId: SessionId, request: MindGardenCreatePhotoStoryRequest) => Promise<RemoteResult<MindGardenCreatePhotoStoryResult>>
    'mindGardenMedia/deletePhotoStory': (agentId: SessionId, request: MindGardenDeletePhotoStoryRequest) => Promise<RemoteResult<MindGardenDeletePhotoStoryResult>>
    'mindGardenMedia/listPhotoStories': (agentId: SessionId, request: MindGardenListPhotoStoriesRequest) => Promise<RemoteResult<MindGardenListPhotoStoriesResult>>
    'mindGardenMedia/observePhotoStory': (agentId: SessionId, request: MindGardenObservePhotoStoryRequest) => Promise<RemoteResult<MindGardenObservePhotoStoryResult>>
    'mindGardenMedia/readPhotoStory': (agentId: SessionId, request: MindGardenReadPhotoStoryRequest) => Promise<RemoteResult<MindGardenReadPhotoStoryResult>>
    'mindGardenMedia/updatePhotoStory': (agentId: SessionId, request: MindGardenUpdatePhotoStoryRequest) => Promise<RemoteResult<MindGardenUpdatePhotoStoryResult>>
  }
  interface TypertRemoteNamespaceMap {
    'mindGardenMedia': TypertRemoteNamespace$6d696e6447617264656e4d65646961
  }
  interface TypertRemoteScopeMap {
    'agent:mindGardenMedia/continuePhotoStory': (request: MindGardenContinuePhotoStoryRequest) => Promise<RemoteResult<MindGardenContinuePhotoStoryResult>>
    'agent:mindGardenMedia/createPhotoStory': (request: MindGardenCreatePhotoStoryRequest) => Promise<RemoteResult<MindGardenCreatePhotoStoryResult>>
    'agent:mindGardenMedia/deletePhotoStory': (request: MindGardenDeletePhotoStoryRequest) => Promise<RemoteResult<MindGardenDeletePhotoStoryResult>>
    'agent:mindGardenMedia/listPhotoStories': (request: MindGardenListPhotoStoriesRequest) => Promise<RemoteResult<MindGardenListPhotoStoriesResult>>
    'agent:mindGardenMedia/observePhotoStory': (request: MindGardenObservePhotoStoryRequest) => Promise<RemoteResult<MindGardenObservePhotoStoryResult>>
    'agent:mindGardenMedia/readPhotoStory': (request: MindGardenReadPhotoStoryRequest) => Promise<RemoteResult<MindGardenReadPhotoStoryResult>>
    'agent:mindGardenMedia/updatePhotoStory': (request: MindGardenUpdatePhotoStoryRequest) => Promise<RemoteResult<MindGardenUpdatePhotoStoryResult>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
